remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
locale: "es-MX"

title: "Yaír Odín Chávez Castro"
author:
  name: "Yaír Odín Chávez Castro"
  bio: "Senior Data Analyst | Actuario | MIT Applied Data Science"

# ESTO ES LO QUE SOLUCIONA EL ERROR:
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
