url: "https://YinRa666.github.io"
baseurl: "/Portafolio-Data-Science"
repository: "YinRa666/Portafolio-Data-Science"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# CONFIGURACIÓN VISUAL
minimal_mistakes_skin: "contrast" # <--- Esto cambiará el azul por gris oscuro/negro
locale: "es-MX"

author:
  name: "Yaír Odín Chávez Castro"
  bio: "Actuario | Senior Data Analyst | MIT Applied Data Science"
  location: "CDMX, México"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yair-chavez-actuary"
    - label: "Gmail"
      icon: "fab fa-fw fa-google"
      url: "https://github.com/YinRa666"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
